M48
; DRILL file {KiCad 8.0.1} date 2024-05-23T14:09:57+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-05-23T14:09:57+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X64.262Y-66.929
X64.262Y-132.207
X203.073Y-66.929
X203.073Y-132.207
M30
