M48
; DRILL file {KiCad 8.0.1} date 2024-05-10T09:13:06+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-05-10T09:13:06+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X64.25Y-61.5
X64.25Y-137.5
X203.073Y-61.5
X203.073Y-137.5
M30
